### PR TITLE
_parseError should be an instance of Error

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Fixes a regression introduced by #319 while still providing a fix for #318.

### CODE REVIEW

**Comment by zaach** [comment]
Thanks ✌🏾

**Comment by liujingbreak** [comment]
Cool, guys, hope you can make an `npm publish` soon, it is quite annoying :)

**Comment by ifreecarve** [comment]
Any word on when this will publish?

**Comment by choumx** [comment]
Would also love this fix published. 😄

**Comment by zaach** [comment]
Ooof, sorry for the delay. 0.4.18 has been published!

**Pull request merged**
